// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlr9F3rhlJ8ju3Ki68LSkyq1JQ-frqAhs',
    appId: '1:293038259746:web:0442d3cfb9da576c8e547b',
    messagingSenderId: '293038259746',
    projectId: 'ancient-tractor-277102',
    authDomain: 'ancient-tractor-277102.firebaseapp.com',
    databaseURL: 'https://ancient-tractor-277102.firebaseio.com',
    storageBucket: 'ancient-tractor-277102.appspot.com',
    measurementId: 'G-1C7MRLXM3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2IUC9yY_TwUpXUxS_e8SugHpqjS8iGlM',
    appId: '1:293038259746:android:091f1dd311203a578e547b',
    messagingSenderId: '293038259746',
    projectId: 'ancient-tractor-277102',
    databaseURL: 'https://ancient-tractor-277102.firebaseio.com',
    storageBucket: 'ancient-tractor-277102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALUf2pJ3TEAy5ZLMnp_lWiDJvMooUKR9w',
    appId: '1:293038259746:ios:5671a620b8fc66878e547b',
    messagingSenderId: '293038259746',
    projectId: 'ancient-tractor-277102',
    databaseURL: 'https://ancient-tractor-277102.firebaseio.com',
    storageBucket: 'ancient-tractor-277102.appspot.com',
    androidClientId: '293038259746-31fvp7o7pfpod9h503smf5bc213d8fgl.apps.googleusercontent.com',
    iosClientId: '293038259746-jdrpcjehff1se154btrcb20mo4s4nftg.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALUf2pJ3TEAy5ZLMnp_lWiDJvMooUKR9w',
    appId: '1:293038259746:ios:5671a620b8fc66878e547b',
    messagingSenderId: '293038259746',
    projectId: 'ancient-tractor-277102',
    databaseURL: 'https://ancient-tractor-277102.firebaseio.com',
    storageBucket: 'ancient-tractor-277102.appspot.com',
    androidClientId: '293038259746-31fvp7o7pfpod9h503smf5bc213d8fgl.apps.googleusercontent.com',
    iosClientId: '293038259746-jdrpcjehff1se154btrcb20mo4s4nftg.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );
}
